# Generated by Django 3.0.6 on 2020-06-07 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('client_mobile', models.CharField(default='0700000000', max_length=20, unique=True)),
                ('client_party', models.CharField(choices=[('defendant', 'Defendant'), ('plaintiff', 'Plaintiff'), ('other', 'Other')], default='other', max_length=20)),
                ('client_age', models.CharField(default='2 Years', max_length=200)),
                ('Other_information', models.TextField()),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'Client_Table',
            },
        ),
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=20)),
                ('court_location', models.CharField(max_length=20)),
                ('court_address', models.CharField(max_length=100)),
                ('court_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Court',
                'verbose_name_plural': 'Courts',
                'db_table': 'Courts_Table',
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('lawyer_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lawyer_mobile', models.CharField(default='0700000000', max_length=20, unique=True)),
                ('lawyer_experience', models.CharField(default='2 Years', max_length=200)),
                ('lawyer_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Lawyer',
                'verbose_name_plural': 'Lawyers',
                'db_table': 'Lawyer_Table',
                'ordering': ['lawyer_username'],
            },
        ),
        migrations.CreateModel(
            name='RePresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presented_to', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Represented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawapp.Lawyer')),
                ('Represented_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawapp.Clients')),
                ('presentation_court', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawapp.Courts')),
            ],
            options={
                'verbose_name': 'Case Re-Presentation',
                'verbose_name_plural': 'Case Re-Presentation',
                'db_table': 'Representation_Table',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('case_title', models.CharField(max_length=200)),
                ('case_unique_key', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('case_document', models.FileField(upload_to='')),
                ('case_description', models.TextField()),
                ('case_status', models.CharField(choices=[('1', 'Accepted'), ('2', 'Rejected'), ('3', 'Awaiting')], default='3', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_owner_username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'Case_Table',
            },
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appearance_date', models.DateTimeField()),
                ('Appearance_status', models.CharField(choices=[('1', 'Present'), ('2', 'Absent'), ('3', 'Closed')], default='2', max_length=10)),
                ('Appearance_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Appearance_court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawapp.Courts')),
                ('Appearing_lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Court Appearance',
                'verbose_name_plural': 'Court Appearances',
                'db_table': 'Appearance_Table',
            },
        ),
    ]
