# Generated by Django 3.0.2 on 2020-01-17 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_mobile', models.CharField(default='0700000000', max_length=20, unique=True)),
                ('lawyer_experience', models.CharField(default='2 Years', max_length=200)),
                ('lawyer_info', models.TextField()),
                ('lawyer_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lawyer',
                'verbose_name_plural': 'Lawyers',
                'db_table': 'Lawyer_Table',
            },
        ),
        migrations.CreateModel(
            name='RePresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presented_to', models.CharField(max_length=200)),
                ('presentation_court', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Represented_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawapp.Lawyer')),
                ('Represented_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Re-Presentation',
                'verbose_name_plural': 'Case (s) Re-Presentation',
                'db_table': 'Representation_Table',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_mobile', models.CharField(default='0700000000', max_length=20, unique=True)),
                ('client_age', models.CharField(default='2 Years', max_length=200)),
                ('client_info', models.TextField()),
                ('client_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'Client_Table',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=200)),
                ('case_unique_key', models.CharField(max_length=200, unique=True)),
                ('case_description', models.TextField()),
                ('case_status', models.CharField(choices=[('1', 'Accepted'), ('2', 'Rejected'), ('3', 'Awaiting')], default='3', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'Case_Table',
            },
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appearance_court', models.CharField(max_length=200)),
                ('Appearance_date', models.DateTimeField()),
                ('Appearance_status', models.CharField(choices=[('1', 'Present'), ('2', 'Absent'), ('3', 'Closed')], default='2', max_length=10)),
                ('Appearance_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Appearing_lawyer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Court Appearance',
                'verbose_name_plural': 'Court Appearances',
                'db_table': 'Appearance_Table',
            },
        ),
    ]
