# Generated by Django 3.0.2 on 2020-01-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Lawyer Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
