# Generated by Django 2.2.2 on 2020-01-19 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0002_auto_20200119_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='id',
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='lawyer_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
