# Generated by Django 3.0.2 on 2020-01-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0002_auto_20200116_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
