# Generated by Django 3.0.2 on 2020-01-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0002_cases_case_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='case_document',
            field=models.FileField(upload_to='media'),
        ),
    ]
