# Generated by Django 2.2.2 on 2020-01-19 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0003_auto_20200119_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='lawyer_username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='representation',
            name='Represented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawapp.Lawyer'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='Represented_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawapp.Clients'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='presentation_court',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawapp.Courts'),
        ),
    ]
