# Generated by Django 2.2.2 on 2020-01-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0004_auto_20200119_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='case_document',
            field=models.FileField(upload_to=''),
        ),
    ]
