# Generated by Django 2.2.2 on 2020-01-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0004_cases_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=20)),
                ('court_location', models.CharField(max_length=20)),
                ('court_address', models.CharField(max_length=100)),
                ('court_desc', models.TextField()),
            ],
            options={
                'verbose_name': 'Court',
                'verbose_name_plural': 'Courts',
                'db_table': 'Courts_Table',
            },
        ),
        migrations.AlterField(
            model_name='representation',
            name='presentation_court',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawapp.Courts'),
        ),
    ]
