# Generated by Django 2.2.2 on 2020-01-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0006_auto_20200119_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='Appearance_court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawapp.Courts'),
        ),
    ]
