# Generated by Django 3.0.2 on 2020-01-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0007_auto_20200119_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyer',
            options={'ordering': ['lawyer_username'], 'verbose_name': 'Lawyer', 'verbose_name_plural': 'Lawyers'},
        ),
    ]
